config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order(Arel.sql('random()')).first
  end

  def new
    @quote = Quote.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Splurty2018</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            You know
            <br />
            you need
            <br />
            to code
          </div>
        <% end %>
      </div>
      <div class="col-4 slogan">
        Splurting out unsolicited advice about entrepreneurship since 2018
      </div>
      <div class="col-5 links">
        <%= link_to 'Contribute', new_quote_path %>
        <%= link_to 'About', '#' %>
      </div>
    </header>

    <hr />

    <br class="clear" />

    <div class="container"> 
      <%= yield %>
    </div> 

    <footer class="footer mt-auto py-3 bg-light">
      <div class="row">
        <div class="col-6">
          <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
        </div>
        <div class="col-6 footer-blurb">
          Proudly hacked by <a href="https://github.com/MarcMcArthur">Marc McArthur</a><br />
          Want to build your own Splurty Web App - <a href="https://online.bootcampspot.com">Learn how to code here</a>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/quotes/index.html.erb
<h1><%= @quote.saying %></h1>
<h2><%= @quote.author %></h2>

app/views/quotes/new.html.erb
<h1>Enter Your Quote Details</h1>

<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>